experiment:
  attacks:
  - ${attack}

attack: null

# ====

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      partitioner: iid
      +datasets: nfv2/sampled/nb15
      batch_size: 32,128,512
      #+epochs: 100/1x100,100/4x25,100/10x10
      +epochs: 100/1x100
      +distribution: 5-5
      +target: untargeted
      +scenario: late-3
      seed: 1138,421,1313,5555,6567,327,2187,1977,501,3263827